services:
  - type: web
    name: cheriyan-studio-api
    env: python
    plan: free
    runtime: python-3.11.9
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python start.py
    healthCheckPath: /docs
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: ALLOWED_HOSTS
        value: https://cheriyan-studio.onrender.com,https://cheriyan-studio-api.onrender.com
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_DIR
        value: app/static/images
      - key: ALLOWED_EXTENSIONS
        value: .jpg,.jpeg,.png,.gif,.webp


